version: "2.1"

jobs:
  UITest:
    docker:
      - image: cimg/node:20.4.0-browsers
    steps:
      - checkout

      - run:
          name: Install Dependencies
          working_directory: UITest
          command: npm install
      - run:
          name: Run tests
          working_directory: UITest
          command: node nightwatch -e chrome -a myStore
      - store_artifacts:
          path: UITest/tests_output/nightwatch-html-report/index.html
          destination: html_reports
  APITest:
    docker:
      - image: cimg/node:20.4.0-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          working_directory: APITest
          command: npm install
     - run:
          name: Install nodemon
          working_directory: APITest
          command: npm install nodemon  
      - run:
          name: Run tests
          working_directory: APITest
          command: npm run dev
      - run:
          name: Run tests
          working_directory: APITest
          command: mocha server.test.js   
      - store_artifacts:
          path: APITest/mochawesome-report/mochawesome.html
          destination: html_reports

workflows:
  test:
    jobs:
      - UITest
      - APITest
