version: "2.1"
orbs:
  browser-tools: circleci/browser-tools@1.4.6

jobs:
  UITest:
    docker:
      - image: cimg/node:20.4.0-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools:
          chrome-version: "118.0.5993.88"
      - run:
          name: Install Dependencies
          working_directory: UITest
          command: npm install
      - run:
          name: Run tests
          working_directory: UITest
          command: node nightwatch -e chrome -a myStore
      - store_artifacts:
          path: UITest/tests_output/nightwatch-html-report/index.html
          destination: html_reports
  APITest:
    docker:
      - image: cimg/node:20.4.0-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          working_directory: APITest
          command: npm install
      - run:
          name: Run tests
          working_directory: APITest
          command: npm run dev
      - run:
          name: Run tests
          working_directory: APITest
          command: mocha server.test.js   
      - store_artifacts:
          path: APITest/mochawesome-report/mochawesome.html
          destination: html_reports

workflows:
  test:
    jobs:
      - UITest
      - APITest
